name: Run Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4          # ← upgrade

    - name: Set up Python
      uses: actions/setup-python@v5      # ← upgrade
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Google Chrome
      run: |
        wget -q -O /usr/share/keyrings/google-linux-signing-key.gpg \
            https://dl.google.com/linux/linux_signing_key.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-key.gpg] \
            http://dl.google.com/linux/chrome/deb/ stable main" | \
            sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get -y install google-chrome-stable

    - name: Run Pytest
      run: pytest -v --html=reports/report.html --self-contained-html

    - name: Upload report artifact
      if: always()
      uses: actions/upload-artifact@v4    # ← upgrade (required)
      with:
        name: test-execution-report
        path: reports/
