name: Run Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chromium
      run: |
        sudo apt-get update
        sudo apt-get -y install chromium-browser
      # On Ubuntu-latest this installs the Snap stub; Selenium still works.

    - name: Run Pytest & create report
      run: |
        mkdir -p reports
        pytest -v tests api --html=reports/report.html --self-contained-html

    - name: Upload HTML report
      if: always()                # runs even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: test-execution-report
        path: reports/
